version: "3.3"

volumes:
    langgraph-data:
        driver: local
services:
    langgraph-redis:
        image: redis:6
        healthcheck:
            test: redis-cli ping
            interval: 5s
            timeout: 1s
            retries: 5
    langgraph-postgres:
        image: postgres:16
        ports:
            - "5433:5432"
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - langgraph-data:/var/lib/postgresql/data
        healthcheck:
            test: pg_isready -U postgres
            timeout: 1s
            retries: 5
            interval: 5s
    langgraph-api:
        image: "my-image"
        ports:
            - "8123:8000"
        depends_on:
        - langgraph-redis
        - langgraph-postgres
        environment:
            REDIS_URI: redis://langgraph-redis:6379
            OPENAI_API_KEY: <YOUR-API-KEY-HERE>
            LANGSMITH_API_KEY: <YOUR-API-KEY-HERE>
            POSTGRES_URI: postgres://postgres:postgres@langgraph-postgres:5432/postgres?sslmode=disable
